volumes:
  rocketchat-data:
    name: rocketchat-data
    external: false
  rocketchat-files:
    name: rocketchat-files
    external: false
  rocketchat-nginx:
    name: rocketchat-nginx
    external: false

services:
  mongodb:
    image: bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    volumes:
      - rocketchat-data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
  rocketchat:
    image: rocket.chat:${RELEASE:-6.7.0}
    depends_on:
      - mongodb
    restart: always
    volumes:
      - rocketchat-files:/app/uploads
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    expose:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
#    ports:
#      - "38120:3000"
  nginx:
    image: nginx:1.27.0-alpine
    depends_on:
      - rocketchat
    volumes:
      - rocketchat-nginx:/var/log/nginx
      - ${UserProfile}/.ssl/127.0.0.1.crt:/root/.ssl/127.0.0.1.crt
      - ${UserProfile}/.ssl/127.0.0.1.key:/root/.ssl/127.0.0.1.key
#      - ${SEUNG_GIT}/seung-note/rocketchat/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ${SEUNG_GIT}/seung-note/rocketchat/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SEUNG_GIT}/seung-note/rocketchat/nginx/default.conf:/etc/nginx/templates/default.conf.template
    environment:
      PORT: "38120"
#    command:
    ports:
      - "38120:443"
