apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: application-name
  newName: [Registry Endpoint]/[Application Name]
  newTag: [Application Version]