apiVersion: v1
kind: Service
metadata:
  name: application-name
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /rest/reflect/get
spec:
  type: NodePort
  selector:
    app: application-name
  ports:
    - name: application-name
      port: 8080
      targetPort: 8080
      nodePort: 32011
